aggregation_model: 1
alpha: 0
area_exploration: '10000'
beta: 10
number_of_asvs: 1
number_of_auvs: 3
number_of_robots: 4
pickle_path: /home/uib/MMRS_ws/src/MMRS_stack/multi_robot_system/missions/pickle/3AUVs/10000.pickle
w1: 0.4
w2: 0.4
w3: 0.2
w4: 0
