aggregation_model: 2
alpha: 0
area_exploration: 50000
beta: 10
number_of_asvs: 1
number_of_auvs: 6
number_of_robots: 7
pickle_path: /home/uib/MMRS_ws/src/MMRS_stack/multi_robot_system/missions/pickle/6AUVs/50000.pickle
w1: 6.72
w2: 2.46
w3: 0.81
w4: 0
