aggregation_model: 2
alpha: 10
area_exploration: '60000'
beta: 0
number_of_asvs: 1
number_of_auvs: 5
number_of_robots: 6
pickle_path: /home/uib/MRS_ws/src/multi_robot_system/missions/pickle/5AUVs/60000.pickle
w1: 0.4
w2: 0.4
w3: 0.2
w4: 0
