aggregation_model: 2
alpha: 7.5
area_exploration: 55000
beta: 2.5
number_of_asvs: 1
number_of_auvs: 6
number_of_robots: 7
pickle_path: /home/uib/MMRS_ws/src/MMRS_stack/multi_robot_system/missions/pickle/6AUVs/55000.pickle
w1: 0.5992
w2: 0.2972
w3: 0.1037
w4: 0
