aggregation_model: 1
alpha: 0
area_exploration: '50000'
beta: 10
number_of_asvs: 1
number_of_auvs: 6
number_of_robots: 7
pickle_path: /home/uib/MRS_ws/src/multi_robot_system/missions/pickle/6AUVs/50000.pickle
w1: 0.4
w2: 0.4
w3: 0.2
w4: 0
