aggregation_model: 2
alpha: 10
area_exploration: '50000'
beta: 0
number_of_asvs: 1
number_of_auvs: 3
number_of_robots: 4
pickle_path: /home/uib/MRS_ws/src/multi_robot_system/missions/pickle/3AUVs/50000.pickle
w1: 0.4
w2: 0.4
w3: 0.2
w4: 0
