# ---------------------------------------------------------
#             MULTI ROBOT SYSTEM CONFIGURATION FILE            
# ---------------------------------------------------------
number_of_robots: 4 #TOTAL number of robots (AUVs+ASVs)
number_of_auvs: 3
number_of_asvs: 1

# NED origin definition
ned_origin_lat: 39.543330
ned_origin_lon: 2.377940

# Exploration area
pickle_path: '/home/uib/MRS_ws/src/multi_robot_system/missions/pickle/3AUVs/5000.pickle'
offset_polygon_distance: 4 # The offset_polygon_distance set the offset distance in order to ensure an enought coverage area between the polygons
offset_coverage_distance: 5 # The offset_coverage_distance set the distance between the coverage lines path

tracking_radius: 30
adrift_radius: 20
repulsion_radius: 10

aggregation_model: 2 # aggregation_model=1 ARTM aggregation_model=2 OWA
transmission_time: 30 # Time [s] spend to transmit objects information acoustically from AUVs to ASV.

# Section strategy parameters
surge_velocity: 1
tolerance: 1

task_allocation: 1
# task_allocator==1 --> Split the tasks depending of the number of robots
# task_allocator==2 --> Assign non consecutive random tasks 
