# ---------------------------------------------------------
#             MULTI ROBOT SYSTEM CONFIGURATION FILE            
# ---------------------------------------------------------

# ------------------ ROBOTS INFO -----------------------
number_of_robots: 5 #TOTAL number of AUVs (explorer robots)
number_of_AUVs: 3
# be sure that all the simulated architectures has the same NED origin 

# Andratx exterior
ned_origin_lat: 39.543330
ned_origin_lon: 2.377940

# ------------------ AREA PARTITION -----------------------
# Exploration area
exploration_area: "/home/uib/MRS_ws/src/multi_robot_system/config/missions/230210085906_cabrera_small.xml"


# SIMULATION PARAMETERS
alpha: 0 
beta: 0
gamma: 10
n: 2


# The offset_polygon_distance set the offset distance in order to ensure an enought coverage area between the polygons
offset_polygon_distance: 5
# The offset_coverage_distance set the distance between the coverage lines path
offset_coverage_distance: 5
# Section strategy parameters
surge_velocity: 1
tolerance: 2

# ------------------ DUSTBIN ROBOT -----------------------
dutsbin_timer: 50

# ------------------ AUV's TASK ALLOCATION -----------------------
task_allocation: 1



        