# ---------------------------------------------------------
#             MULTI ROBOT SYSTEM CONFIGURATION FILE            
# ---------------------------------------------------------
number_of_robots: 5 #TOTAL number of robots (AUVs+ASVs)

# NED origin definition
ned_origin_lat: 39.543330
ned_origin_lon: 2.377940

# Exploration area
exploration_area: "/home/uib/MRS_ws/src/multi_robot_system/config/missions/230210085906_cabrera_small.xml"
pickle_path: '/home/uib/MRS_ws/src/multi_robot_system/config/mission.pickle'
offset_polygon_distance: 5 # The offset_polygon_distance set the offset distance in order to ensure an enought coverage area between the polygons
offset_coverage_distance: 5 # The offset_coverage_distance set the distance between the coverage lines path

# Section strategy parameters
surge_velocity: 2
tolerance: 2

task_allocation: 1
# task_allocator==1 --> Split the tasks depending of the number of robots
# task_allocator==2 --> Assign non consecutive random tasks 




        