# ---------------------------------------------------------
#             MULTI ROBOT SYSTEM CONFIGURATION FILE            
# ---------------------------------------------------------

# ------------------ ROBOTS INFO -----------------------
number_of_robots: 3
# be sure that all the simulated architectures has the same NED origin (Bendinat)
ned_origin_lat: 39.14803625
ned_origin_lon: 2.93195323

# ------------------ AREA PARTITION -----------------------
# Exploration area
exploration_area: "/home/uib/MRS_ws/src/MRS_stack/multi_robot_system/missions/230210085906_cabrera_small.xml"
# The offset_polygon_distance set the offset distance in order to ensure an enought coverage area between the polygons
offset_polygon_distance: 5
# The offset_coverage_distance set the distance between the coverage lines path
offset_coverage_distance: 10
# Section strategy parameters
surge_velocity: 0.8
tolerance: 2

# ------------------ DUSTBIN ROBOT -----------------------
dutsbin_timer: 120

# ------------------ TASK ALLOCATION -----------------------
task_allocation: 1

#Task allocation strategies

# 1 Split the tasks depending of the number of robots
#  Divide the tasks between the number of robots and assign tasks to each robot
#  example:Tasks [0,1,2,3,4]-> r1_tasks[0,1,2], r2_tasks[3,4]

# 2 Assign non consecutive random tasks
# Assign the nearest polygon to the robot_0, and decide wich is the task for the robot_1. Tasks mustn't be consecutive.
# example:Tasks [0,1,2,3,4]-> r1_tasks[3,4,0], r2_tasks[1,2]

# 3 Hungarian algorithm



        