# ---------------------------------------------------------
#             MULTI ROBOT SYSTEM CONFIGURATION FILE            
# ---------------------------------------------------------

# ------------------ ROBOTS INFO -----------------------
number_of_robots: 3
robot_1: turbot1
robot_2: turbot2
robot_3: xiroi
navigation_topic_robot_1: /turbot1/navigator/navigation
navigation_topic_robot_2: /turbot2/navigator/navigation
navigation_topic_robot_3: /turbot3/navigator/navigation

# ------------------ AREA PARTITION -----------------------
# The offset_polygon_distance set the offset distance in order to ensure an enought coverage area between the polygons
offset_polygon_distance: 5
# The offset_coverage_distance set the distance between the coverage lines path
offset_coverage_distance: 3
# Section strategy parameters
surge_velocity: 0.8
tolerance: 2

# ------------------ TASK ALLOCATION -----------------------

task_allocation: 1

#Task allocation strategies

# 1 Split the tasks depending of the number of robots
#  Divide the tasks between the number of robots and assign tasks to each robot
#  example:Tasks [0,1,2,3,4]-> r1_tasks[0,1,2], r2_tasks[3,4]

# 2 Assign non consecutive random tasks
# Assign the nearest polygon to the robot_0, and decide wich is the task for the robot_1. Tasks mustn't be consecutive.
# example:Tasks [0,1,2,3,4]-> r1_tasks[3,4,0], r2_tasks[1,2]

# 3 Hungarian algorithm



        