grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: elevation
     
  - name: elevation_grid
    type: occupancy_grid
    params:
     layer: elevation
     data_min: -10
     data_max: 0

  - name: ASV_data
    type: elevation
    params:
     layer: ASV
     data_min: -10
     data_max: -0.16

  - name: AUV_data
    type: elevation
    params:
     layer: AUV
     data_min: -10
     data_max: -0.16  